import { User, Building, Facility, ConstructionEvent, FAQ, Notification } from './types';

// Mock Buildings
export const mockBuildings: Building[] = [
  {
    id: 'bldg-001',
    name: 'シティタワー東京',
    address: '東京都渋谷区',
    totalFloors: 35,
    totalUnits: 280,
    managementCompany: '三菱地所リアルティ',
    features: [
      { id: 'fac-001', name: '駐車場 B1F', buildingId: 'bldg-001', floor: -1, type: 'parking' },
      { id: 'fac-002', name: 'フィットネスジム', buildingId: 'bldg-001', floor: 2, type: 'gym' },
      { id: 'fac-003', name: 'ロビー', buildingId: 'bldg-001', floor: 1, type: 'lobby' },
      { id: 'fac-004', name: 'ラウンジ', buildingId: 'bldg-001', floor: 30, type: 'common' },
    ],
  },
];

// Mock Current User
export const mockCurrentUser: User = {
  id: 'user-001',
  email: 'resident@example.com',
  displayName: 'Tanaka Taro',
  role: 'resident',
  buildingId: 'bldg-001',
  floorNumber: 15,
  unitNumber: '1501',
  facilitiesOfInterest: ['fac-002', 'fac-003'],
  timePreferences: [
    { startHour: 7, endHour: 9, label: '朝間工事' },
    { startHour: 19, endHour: 23, label: '夜間工事' },
  ],
  createdAt: new Date('2024-01-01'),
};

// Mock Construction Events
export const mockConstructionEvents: ConstructionEvent[] = [
  {
    id: 'event-001',
    buildingId: 'bldg-001',
    title: '駐車場整備工事',
    description: 'B1Fの駐車場全体の床材改修工事を行います',
    type: 'construction',
    status: 'in_progress',
    startDate: new Date('2025-02-15'),
    endDate: new Date('2025-03-10'),
    startTime: '09:00',
    endTime: '17:00',
    affectedFloors: [],
    affectedFacilities: ['fac-001'],
    affectedAreas: ['駐車場全体'],
    noiseLevel: 'high',
    accessRestrictions: true,
    details: '安全確保のため、工事期間中は駐車スペースが限定されます。詳細は別途掲示板にてお知らせします。',
    contractor: '関電工',
    contactPerson: '田中太郎',
    contactPhone: '03-XXXX-XXXX',
    createdAt: new Date('2025-02-01'),
    updatedAt: new Date('2025-02-10'),
  },
  {
    id: 'event-002',
    buildingId: 'bldg-001',
    title: 'ジム設備メンテナンス',
    description: '定期的な設備点検とメンテナンスを行います',
    type: 'maintenance',
    status: 'scheduled',
    startDate: new Date('2025-02-25'),
    endDate: new Date('2025-02-25'),
    startTime: '18:00',
    endTime: '21:00',
    affectedFloors: [],
    affectedFacilities: ['fac-002'],
    affectedAreas: ['2階ジム'],
    noiseLevel: 'low',
    accessRestrictions: true,
    details: '夜間のみの工事となります。ジムは使用不可になります。',
    contractor: '施設管理会社',
    createdAt: new Date('2025-02-05'),
    updatedAt: new Date('2025-02-10'),
  },
  {
    id: 'event-003',
    buildingId: 'bldg-001',
    title: '外壁調査',
    description: 'ビル全体の外壁状況調査を実施',
    type: 'inspection',
    status: 'scheduled',
    startDate: new Date('2025-03-01'),
    endDate: new Date('2025-03-15'),
    startTime: '08:00',
    endTime: '18:00',
    affectedFloors: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    affectedFacilities: [],
    affectedAreas: ['北側外壁', '東側外壁'],
    noiseLevel: 'medium',
    accessRestrictions: false,
    details: '足場を組んで調査します。音や振動が発生する可能性があります。',
    contractor: '建築診断会社',
    contactPerson: '佐藤花子',
    contactPhone: '03-YYYY-YYYY',
    createdAt: new Date('2025-02-01'),
    updatedAt: new Date('2025-02-10'),
  },
  {
    id: 'event-004',
    buildingId: 'bldg-001',
    title: 'ロビーリノベーション',
    description: 'ロビーのインテリアリノベーション',
    type: 'construction',
    status: 'scheduled',
    startDate: new Date('2025-03-20'),
    endDate: new Date('2025-04-30'),
    startTime: '10:00',
    endTime: '18:00',
    affectedFloors: [],
    affectedFacilities: ['fac-003'],
    affectedAreas: ['1階ロビー'],
    noiseLevel: 'high',
    accessRestrictions: false,
    details: '営業時間中の工事となります。騒音が発生しますがご理解よろしくお願いします。',
    contractor: '内装工事会社',
    createdAt: new Date('2025-02-08'),
    updatedAt: new Date('2025-02-10'),
  },
];

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: 'notif-001',
    userId: 'user-001',
    eventId: 'event-001',
    title: '駐車場工事が進行中です',
    message: '駐車場整備工事は予定通り進行中です。駐車スペースは限定されています。',
    type: 'event_update',
    isRead: false,
    createdAt: new Date('2025-02-18'),
  },
  {
    id: 'notif-002',
    userId: 'user-001',
    eventId: 'event-002',
    title: 'ジムメンテナンスのお知らせ',
    message: '2月25日(火) 18:00～21:00、ジムのメンテナンスのため使用できません。',
    type: 'new_event',
    isRead: true,
    createdAt: new Date('2025-02-15'),
  },
  {
    id: 'notif-003',
    userId: 'user-001',
    eventId: 'event-003',
    title: '外壁調査が3月に開始します',
    message: 'あなたの部屋の周辺で3月1日～15日に外壁調査が実施されます。',
    type: 'new_event',
    isRead: true,
    createdAt: new Date('2025-02-10'),
  },
];

// Mock FAQs
export const mockFAQs: FAQ[] = [
  {
    id: 'faq-001',
    buildingId: 'bldg-001',
    category: '工事について',
    question: '工事中は騒音がありますか？',
    answer: '工事の種類によって異なります。高い騒音が予想される工事は事前にお知らせします。詳細は各工事のページをご確認ください。',
    order: 1,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'faq-002',
    buildingId: 'bldg-001',
    category: '工事について',
    question: '工事期間中は部屋の中に入れませんか？',
    answer: '通常の工事では、共有スペースの工事が多く、部屋へのアクセスは制限されません。ただし、特定の工事では通路が一時的に制限されることがあります。',
    order: 2,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'faq-003',
    buildingId: 'bldg-001',
    category: '通知について',
    question: 'なぜ特定の工事のお知らせだけが届くのですか？',
    answer: 'あなたの住んでいるフロアや利用している施設に関連した工事のお知らせが優先的に表示されます。これがパーソナライズ機能です。',
    order: 1,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'faq-004',
    buildingId: 'bldg-001',
    category: '質問について',
    question: '質問フォームで問い合わせた場合、回答までにどのくらい時間がかかりますか？',
    answer: 'お問い合わせいただいてから、通常2営業日以内に回答いたします。緊急の場合は電話でお問い合わせください。',
    order: 2,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];
